feature_extract_enable : 0
point_filter_num : 2
max_iteration : 10
dense_map_enable : 0

filter_size_surf : 0.05 #0.05~0.15 for indoor scenes, 0.3~0.5 for outdoor scenes.
filter_size_map : 0.15 #0.15~0.3 for indoor scenes, 0.4~0.5 for outdoor scenes

cube_side_length : 20
debug : 0
grid_size : 40
patch_size : 8

img_enable : 1 #enable vio
lidar_enable : 1 #enable lio

# The outlier threshold value of photometric error (square) of a single pixel. 
# It is recommended that 50~250 for the darker scenes, 500~1000 for the brighter scenes. 
# The smaller the value is, the faster the vio submodule is, but the weaker the anti-degradation ability is. '''
outlier_threshold : 50 # 78 100 156

ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.001 # 0.001

cam_fx: 696.7174426776
cam_fy: 696.4862496732
cam_cx: 708.4206218964
cam_cy: 535.6712007522

common:
    # lid_topic:  "/livox/lidar"
    lid_topic:  "os_cloud_node/points"
    imu_topic:  "/alphasense/imu"

preprocess:
    lidar_type: 3 # Livox Avia LiDAR
    scan_line: 6
    blind: 5 # blind x m disable

mapping:
    acc_cov_scale: 100
    gyr_cov_scale: 10000
    # acc_cov_scale: 10
    # gyr_cov_scale: 100
    fov_degree:    90
    
    # # transform: Lidar to IMU - Livox
    # extrinsic_T: [-0.003050707070885951, -0.021993853931529066, 0.15076415229379997]
    # extrinsic_R: [ 0.9998, 0.0170, -0.007,
    #                0.0171, -0.9997, 0.017,
    #                -0.0067, -0.0171, -0.9998]
    
    # transform: Lidar to IMU - Ouster
    extrinsic_T: [0.01001966915517371, -0.006645473484212856, 0.09473042428051345]
    extrinsic_R: [  0.9999757,  0.0024556, -0.0065197,
                    0.0024579, -0.9999969,  0.0003309,
                    -0.0065188, -0.0003470, -0.9999787 ]
camera:
    # img_topic: /usb_cam/image_raw
    # img_topic:  /camera/image_color
    img_topic: /alphasense/cam1/image_raw
    #xiyuan
    #camera 1 to imu transformation
    Rcl: [-0.0027313,  0.0012467,  0.9999955,
           0.9999905,  0.0033916,  0.0027270,
          -0.0033882,  0.9999934, -0.0012560 ]
    Pcl: [0.0507054642910155, -0.060959522169800155, -0.005930631162279414]
    
